ALTER TABLE "Invoice" ADD COLUMN "issuerTaxId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "issuerAddress" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "customerCity" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "customerPhone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "servicePeriod" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "paymentTerms" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "observations" TEXT NOT NULL DEFAULT '';